### ISSUE TITLE
can you please provide scipt for converting data in csv format?

### ISSUE THREAD

**Issue by akashAD98** [pereldegla/yoga_assistant#1]
im getting error while importing my custom data which has 51 features, but your data has 132, also it would be great if you can add detailed steps regarding model training @pereldegla

**Comment by pereldegla** [comment]
hello, check the "build_dataset" function in utils.py

About the model training, it could be better since I used a "default" configuration without any tweaks. Free free to change that with some gridsearch and cross validation

**Comment by akashAD98** [comment]
@pereldegla i got it thanks
